### ISSUE TITLE
repo URL in repo.pp

### ISSUE THREAD

**Issue by valerioj** [Graylog2/graylog2-puppet#19]
i think the repo URL should not contain the part "/repo" anymore... this URL is invalid:

https://packages.graylog2.org/repo/el/6Server/1.0/x86_64/repodata

this one is OK:

https://packages.graylog2.org/el/6Server/1.0/x86_64/repodata

the same probably applies for the debian repo.

**Comment by joschi** [comment]
Thanks for reporting this, but the URLs are actually correct.

The URL of the browsable repository (https://packages.graylog2.org/el/6Server/1.0/x86_64/repodata) is different from the actual download URL (e. g. https://packages.graylog2.org/repo/el/6Server/1.0/x86_64/repodata/repomd.xml).
