### ISSUE TITLE
support puppetlabs-apt 2.0.0

### ISSUE THREAD

**Issue by mmarod** [Graylog2/graylog2-puppet#21]
This module requires 1.0 <= puppetlabs-apt < 2.0 ... It would be great to be able to use 2.0 with it

**Comment by rlex** [comment]
basically, 
```
include_src       => false,
``` 

Should be removed to make it compatible. Have not yet looked at $pin var.

**Comment by mmarod** [comment]
While this may fix the issue -- I still can't use librarian-puppet or r10k with this module and apt/2.x because the metadata.json file has a strict requirement on <2.0.0 so I get a dependency resolution error.

**Comment by taik0** [comment]
Seems that they don't support this module anymore? Almost a year with dependency problems.
Or maybe the don't care anymore. Pretty sad.
```
Error: Could not install module 'graylog2-graylog2' (???)
  No version of 'graylog2-graylog2' can satisfy all dependencies
    Use `puppet module install --ignore-dependencies` to install only this module
```

**Comment by naxhh** [comment]
Any reason to not have this fixed yet?

**Comment by joschi** [comment]
@naxhh Pull requests for improving this Puppet module are welcome!

**Comment by taik0** [comment]
Please check the PR #37

**Comment by bernd** [comment]
We started a new puppet module for Graylog 2.0 over at https://forge.puppet.com/graylog/graylog.

This one only works for Graylog 1.x and will be deprecated. So we are probably not add apt 2.0 support. Sorry.
