### ISSUE TITLE
RPMs and Java 7, 8

### ISSUE THREAD

**Issue by valerioj** [Graylog2/graylog2-puppet#22]
Hello. I'm using the Puppet modules to automatically install Graylog, and I found out that the Graylog packages require "java >= 1:1.7.0".

The problem is that java-1.8.0-openjdk provides "java = 1.8.0", i.e. they dropped the epoch notation "1:" in this version.

The result is that the RPMs will ask for version 1.7 even if version 8 is installed.

An alternative could be that the RPM requires jre >= 1.7.0 instead of java, which has the same notation for both versions (1.7.0 and 1.8.0 respectively).

Would it be possible to change that? Do you think of other alternatives?

Thanks in advance.

**Comment by bernd** [comment]
This has been addressed in Graylog2/fpm-recipes#34.

**Comment by valerioj** [comment]
thanks for the help!
