### ISSUE TITLE
Support for Graylog 1.1 (for example MongoDB URIs)

### ISSUE THREAD

**Issue by linuxprofessor** [Graylog2/graylog2-puppet#24]
Support for the newly released Graylog 1.1 is needed.

An example of this is the "old" form of MongoDB configuration is now deprecated in favor of MongoDB URI, this should be added/changed

**Comment by linuxprofessor** [comment]
Made changed to reflect this, see https://github.com/Graylog2/graylog2-puppet/pull/25

**Comment by ofalk** [comment]
I'm about to upgrade to 1.1 and would also love to see this gets merged.

**Comment by linuxprofessor** [comment]
This is now merged.
