### ISSUE TITLE
service is not restarted when the package is updated

### ISSUE THREAD

**Issue by valerioj** [Graylog2/graylog2-puppet#27]
Hello, i'm using your puppet modules and i've noticed that when the package is updated, i have to restart all services by hand... this is not a desired method if, for example, we want to achieve full automation and 0 human interaction for maintenance...

i would suggest to add this line into the package.pp modules:

class graylog2::server::package(
  $package,
  $version,
) {

  package { $package:
    ensure  => $version,
#new line:
    notify => Service[$package],
  }

}

Thanks in advance

**Comment by bernd** [comment]
I am not sure if I want to add that dependency to the package class. You might not want to restart the service after an update in any case.

You can use `Graylog2::Server::Package["graylog-server"] ~> Service["graylog-server"]` to define that dependency and notification.

Any other opinions?

**Comment by kroepke** [comment]
I agree that forcing automatic restarting is not a good option as a default behavior, because it can interrupt the service.
If it is possible to define that restarting behavior easily and is clearly documented, I would vote for keeping the current state.

**Comment by bernd** [comment]
The dependency notation I mentioned above is standard Puppet syntax and can be used to restart the service after a package update.

Closing this issue now.

**Comment by valerioj** [comment]
it is ok, i will do it like that. thanks.
